package com.ihub.model;
// Generated 30 Apr, 2019 1:31:00 PM by Hibernate Tools 4.3.1
/**
 * Defaultup generated by hbm2java
 */
public class Defaultup  implements java.io.Serializable {


     private int serialNo;
     private String userName;
     private String password;
     private String item;
     private String portNo;
     private String brand;

    public Defaultup() {
    }

	
    public Defaultup(int serialNo) {
        this.serialNo = serialNo;
    }
    public Defaultup(int serialNo, String userName, String password, String item, String portNo, String brand) {
       this.serialNo = serialNo;
       this.userName = userName;
       this.password = password;
       this.item = item;
       this.portNo = portNo;
       this.brand = brand;
    }
   
    public int getSerialNo() {
        return this.serialNo;
    }
    
    public void setSerialNo(int serialNo) {
        this.serialNo = serialNo;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getItem() {
        return this.item;
    }
    
    public void setItem(String item) {
        this.item = item;
    }
    public String getPortNo() {
        return this.portNo;
    }
    
    public void setPortNo(String portNo) {
        this.portNo = portNo;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }




}


