package com.ihub.model;
// Generated 30 Apr, 2019 1:31:00 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private Integer serialno;
     private String id;
     private String password;

    public Login() {
    }

    public Login(String id, String password) {
       this.id = id;
       this.password = password;
    }
   
    public Integer getSerialno() {
        return this.serialno;
    }
    
    public void setSerialno(Integer serialno) {
        this.serialno = serialno;
    }
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


