package com.ihub.model;
// Generated 30 Apr, 2019 1:31:00 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String id;
     private String password;
     private String deviceinfo;

    public User() {
    }

	
    public User(String id) {
        this.id = id;
    }
    public User(String id, String password, String deviceinfo) {
       this.id = id;
       this.password = password;
       this.deviceinfo = deviceinfo;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getDeviceinfo() {
        return this.deviceinfo;
    }
    
    public void setDeviceinfo(String deviceinfo) {
        this.deviceinfo = deviceinfo;
    }




}


